package org.openmrs.module.epts.etl.utilities.tools;


import java.util.LinkedHashSet;
import java.util.Set;

public class RemoveDuplications {

    public static void main(String[] args) {

        String text = "Moçambicana\n"
        		+ "Mocambicano\n"
        		+ "Inhambane\n"
        		+ "MANJACAZE\n"
        		+ "MARRACUENE\n"
        		+ "INHARRIME\n"
        		+ "MAPUTO\n"
        		+ "Mocambique\n"
        		+ "Mocanbicano\n"
        		+ "Moacambicana\n"
        		+ "mocambica\n"
        		+ "mocambicaca\n"
        		+ "quelimane\n"
        		+ "Mocambicanba\n"
        		+ "Mocambicane\n"
        		+ "moçambicano\n"
        		+ "Mocanbicana\n"
        		+ "Macambicana\n"
        		+ "Mocambico\n"
        		+ "Mocambica\n"
        		+ "Manhica\n"
        		+ "Moambicana\n"
        		+ "Mozambicana\n"
        		+ "Moçambique\n"
        		+ "Moamba\n"
        		+ "Maputo\n"
        		+ "Mo;ambicana\n"
        		+ "Mocambiacana\n"
        		+ "Mocambicacna\n"
        		+ "Mocanbicano\n"
        		+ "Maputo/Manhica\n"
        		+ "Munguine\n"
        		+ "Moçambicana:\n"
        		+ "INHAMBANE\n"
        		+ "m\n"
        		+ "MATOLA\n"
        		+ "mo\n"
        		+ "Mozambique\n"
        		+ "Africa de Sul\n"
        		+ "Congoleza\n"
        		+ "Zimbabwe\n"
        		+ "Sul Africana\n"
        		+ "Gaza\n"
        		+ "Inhanbane\n"
        		+ "Congolese\n"
        		+ "Nigeriano\n"
        		+ "Mocambicaca\n"
        		+ "Burundesa\n"
        		+ "zimbabwiana\n"
        		+ "Moccambicana\n"
        		+ "Mocabicana\n"
        		+ "Mocamicana\n"
        		+ "Zimbabweana\n"
        		+ "mocambicanao\n"
        		+ "Mcambicana\n"
        		+ "Moçambicana\n"
        		+ "Moçambicano\n"
        		+ "mocambique\n"
        		+ "Mo;ambicana\n"
        		+ "Mcambicana\n"
        		+ "Mocanbicana\n"
        		+ "Mocanbicano\n"
        		+ "Mo;ambi\n"
        		+ "m\n"
        		+ "Mocambicane\n"
        		+ "MOCAMBICABA\n"
        		+ "Mocambican\n"
        		+ "chokwe\n"
        		+ "Moc\n"
        		+ "Moncambicano\n"
        		+ "Mocambinca\n"
        		+ "Mocambicanao\n"
        		+ "mocaambicana\n"
        		+ "mocaambicano\n"
        		+ "sul Africana\n"
        		+ "Moca\n"
        		+ "Mozambique\n"
        		+ "macambicana\n"
        		+ "maocambicana\n"
        		+ "Mocambocano\n"
        		+ "Moçaçambicana\n"
        		+ "Moçambicvana\n"
        		+ "Mocmbicana\n"
        		+ "Mocmbicano\n"
        		+ "Mocabincana\n"
        		+ "Mocambicanas\n"
        		+ "Mocambica\n"
        		+ "Moçcambica\n"
        		+ "Mocambiqiue\n"
        		+ "Mocambicaca\n"
        		+ "Moacambicano\n"
        		+ "Moacambicana\n"
        		+ "Mocambicanaa\n"
        		+ "Mocambiicana\n"
        		+ "Mocabicana\n"
        		+ "Mocabicano\n"
        		+ "Zimbawbweana\n"
        		+ "Mocambican0\n"
        		+ "Moz\n"
        		+ "Mo\n"
        		+ "Mocambicanoa\n"
        		+ "Mocambicaco\n"
        		+ "Macambicano\n"
        		+ "Mocambica na\n"
        		+ "Mocambacana\n"
        		+ "Mocamnbicana\n"
        		+ "Mocambacano\n"
        		+ "Moicambicano\n"
        		+ "Mozambican\n"
        		+ "Mocambicana\n"
        		+ "Mocambicano\n"
        		+ "Mocabicana\n"
        		+ "Macambicana\n"
        		+ "Mocambiacna\n"
        		+ "Mocambican\n"
        		+ "ma\n"
        		+ "Maxixe\n"
        		+ "Mocambique\n"
        		+ "Inhambane\n"
        		+ "moca\n"
        		+ "mocambicanoa\n"
        		+ "Mocambica\n"
        		+ "m\n"
        		+ "CS Muele\n"
        		+ "Macabicana\n"
        		+ "Mocambuicana\n"
        		+ "Mocambicana\n"
        		+ "Moçambicano\n"
        		+ "Mocambica\n"
        		+ "Macambicana\n"
        		+ "Caia\n"
        		+ "m\n"
        		+ "Mocambican0\n"
        		+ "Mocambique\n"
        		+ "MocambicanaArmando\n"
        		+ "Mocambicanob\n"
        		+ "Mocambicanabb\n"
        		+ "Mocambicanab\n"
        		+ "Mozambicano\n"
        		+ "Malawiano\n"
        		+ "Mo\n"
        		+ "Mocambiana\n"
        		+ "Macambicano\n"
        		+ "Moçambicamo\n"
        		+ "Mocambican\n"
        		+ "Beira\n"
        		+ "Zimbabwe\n"
        		+ "Inhambane\n"
        		+ "Mcambique\n"
        		+ "Nampula\n"
        		+ "Cabo - Delegado\n"
        		+ "Munhava\n"
        		+ "Mocamicana\n"
        		+ "Mocambicanoa\n"
        		+ "Chimoio\n"
        		+ "Mocambicambica\n"
        		+ "Mo;ambicana\n"
        		+ "Massinga -Inhambane\n"
        		+ "Mocamicano\n"
        		+ "Mocambicana\n"
        		+ "Mocambicano\n"
        		+ "mocabincana\n"
        		+ "mocabincano\n"
        		+ "ZIMBABWANO\n"
        		+ "zimbabwana\n"
        		+ "Zimbabwe- Honde vale\n"
        		+ "zimbababue\n"
        		+ "Mocambiquicano\n"
        		+ "zimbabwe\n"
        		+ "zimbabweana\n"
        		+ "zimbzbweano\n"
        		+ "Mocambico\n"
        		+ "MOCAMBICAN0\n"
        		+ "Moçambique\n"
        		+ "Mocanbicana\n"
        		+ "Sofala\n"
        		+ "Moacambicana\n"
        		+ "Mutarara -Tete\n"
        		+ "Chimoio\n"
        		+ "Gondola\n"
        		+ "Mocambicane\n"
        		+ "M0cambicana\n"
        		+ "MACAMBICANA\n"
        		+ "mocabincan0\n"
        		+ "Manica\n"
        		+ "Mocambica\n"
        		+ "mocabicano\n"
        		+ "Mocanbicano\n"
        		+ "Mocabicana\n"
        		+ "Mocambicana\n"
        		+ "Macambicana\n"
        		+ "Macambicano\n"
        		+ "Moçambicano\n"
        		+ "Mocabicana\n"
        		+ "Zimbabweana\n"
        		+ "Malawiana\n"
        		+ "Mocambique\n"
        		+ "mocanbicana\n"
        		+ "Mocambicaca\n"
        		+ "Mocambicaba\n"
        		+ "Mocambincana\n"
        		+ "Manica-Tambara\n"
        		+ "tete\n"
        		+ "Moçambicana\n"
        		+ "Mocambicano\n"
        		+ "MACAMBICANA\n"
        		+ "MOCANBICANA\n"
        		+ "MOCAMBIQUE\n"
        		+ "Namacurra\n"
        		+ "Moçamnbicana\n"
        		+ "MOCAMBICACA\n"
        		+ "Morrumbala\n"
        		+ "Nigeriana\n"
        		+ "Mocambcana\n"
        		+ "Quelimane\n"
        		+ "Mocanbique\n"
        		+ "Malawiana\n"
        		+ "Zambezia\n"
        		+ "Moc\n"
        		+ "Monçambicana\n"
        		+ "Mozambicana\n"
        		+ "Moacmbicana\n"
        		+ "Mocamicana\n"
        		+ "Moçambicana\n"
        		+ "Mocambicano\n"
        		+ "Natural de Mali\n"
        		+ "Nampula\n"
        		+ "Mocanbicana\n"
        		+ "Moçambique\n"
        		+ "mocabicano\n"
        		+ "Moçambicana\n"
        		+ "Mocambicano\n"
        		+ "Moçabicana\n"
        		+ "Maocambicana\n"
        		+ "Nigeria\n"
        		+ "Macambicana\n"
        		+ "Mozambican\n"
        		+ "Nocambiçana\n"
        		+ "Moçambique\n"
        		+ "Maocambicano\n"
        		+ "macambicano\n"
        		+ "mocabicano\n"
        		+ "Maputo\n"
        		+ "Pemba\n"
        		+ "Metugi\n"
        		+ "Cabo Delgado\n"
        		+ "Quilimane\n"
        		+ "Moçambicanoa\n"
        		+ "Chiure Velho\n"
        		+ "Mocambican\n"
        		+ "Moçambicanac\n"
        		+ "Moçambicanaa\n"
        		+ "Chiure\n"
        		+ "Mocanbicana\n"
        		+ "Muidumbe\n"
        		+ "Mocambicao\n"
        		+ "Mocamicano\n"
        		+ "Mocambicanio\n"
        		+ "Mocambina\n"
        		+ "Mocamibicano\n"
        		+ "Mocanbicano\n"
        		+ "Moca\n"
        		+ "Mocambiquicana\n"
        		+ "Mocamcana\n"
        		+ "Miocambicana\n"
        		+ "Mocambicna\n"
        		+ "Manrasse\n"
        		+ "Mocambicanos\n"
        		+ "Mocan\n"
        		+ "Mocambiicana\n"
        		+ "Mocambiacana\n"
        		+ "Moxca\n"
        		+ "Mocambiocana\n"
        		+ "Mocambica\n"
        		+ "Movambicana\n"
        		+ "moncambicana\n"
        		+ "Guinne\n"
        		+ "Tanzaniana\n"
        		+ "Montepuez\n"
        		+ "Maliano\n"
        		+ "Malawiana\n"
        		+ "Santomenssa\n"
        		+ "Guinessa\n"
        		+ "Moncambique\n"
        		+ "Mocmbicana\n"
        		+ "Mocamnicano\n"
        		+ "Momcabicana\n"
        		+ "Tanzaniano\n"
        		+ "Niassa\n"
        		+ "Guines\n"
        		+ "Guine Conacri\n"
        		+ "Guninenssa\n"
        		+ "Mocambicaana\n"
        		+ "Mocambhicana\n"
        		+ "Mocamcano\n"
        		+ "Mueda\n"
        		+ "Moçambicano\n"
        		+ "Moçambicana\n"
        		+ "Mcambicana\n"
        		+ "MOCAMBIQUE\n"
        		+ "Cuamba\n"
        		+ "Mocmbique\n"
        		+ "Malawiana\n"
        		+ "Moca\n"
        		+ "Mocabicana\n"
        		+ "Mocabicano\n"
        		+ "Mocambino\n"
        		+ "Nampula\n"
        		+ "Zambezia\n"
        		+ "Niassa\n"
        		+ "Angonia\n"
        		+ "malawiano\n"
        		+ "Maputo\n"
        		+ "Gaza\n"
        		+ "Cabo Delgado\n"
        		+ "Xaixai\n"
        		+ "Mecula\n"
        		+ "Moçambican\n"
        		+ "Climane\n"
        		+ "Mocabincana";

        Set<String> unique = new LinkedHashSet<>();

        for (String line : text.split("\\R")) {
            line = line.trim();
            if (!line.isEmpty()) {
                unique.add(line);
            }
        }

        unique.forEach(System.out::println);
    }
}
