package org.openmrs.module.epts.etl.conf;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;

import org.openmrs.module.epts.etl.conf.interfaces.EtlAdditionalDataSource;
import org.openmrs.module.epts.etl.conf.interfaces.EtlDataConfiguration;
import org.openmrs.module.epts.etl.conf.interfaces.EtlDataSource;
import org.openmrs.module.epts.etl.conf.interfaces.ParentTable;
import org.openmrs.module.epts.etl.conf.interfaces.TableAliasesGenerator;
import org.openmrs.module.epts.etl.conf.interfaces.TableConfiguration;
import org.openmrs.module.epts.etl.exceptions.ForbiddenOperationException;
import org.openmrs.module.epts.etl.model.Field;
import org.openmrs.module.epts.etl.utilities.db.conn.DBException;
import org.openmrs.module.epts.etl.utilities.db.conn.DBUtilities;
import org.openmrs.module.epts.etl.utilities.db.conn.OpenConnection;

import com.fasterxml.jackson.annotation.JsonIgnore;

public class SrcConf extends AbstractTableConfiguration implements EtlDataSource, TableAliasesGenerator {
	
	private List<AuxExtractTable> selfJoinTables;
	
	private List<TableDataSourceConfig> extraTableDataSource;
	
	private List<QueryDataSourceConfig> extraQueryDataSource;
	
	private List<String> autoGeneratedAliases;
	
	private boolean fullLoaded;
	
	public List<AuxExtractTable> getSelfJoinTables() {
		return selfJoinTables;
	}
	
	public void setSelfJoinTables(List<AuxExtractTable> selfJoinTables) {
		this.selfJoinTables = selfJoinTables;
	}
	
	public List<QueryDataSourceConfig> getExtraQueryDataSource() {
		return extraQueryDataSource;
	}
	
	public void setExtraQueryDataSource(List<QueryDataSourceConfig> extraQueryDataSource) {
		this.extraQueryDataSource = extraQueryDataSource;
	}
	
	public List<TableDataSourceConfig> getExtraTableDataSource() {
		return extraTableDataSource;
	}
	
	public void setExtraTableDataSource(List<TableDataSourceConfig> extraTableDataSource) {
		this.extraTableDataSource = extraTableDataSource;
	}
	
	@Override
	public String getName() {
		return getTableName();
	}
	
	@Override
	public boolean isGeneric() {
		return false;
	}
	
	@Override
	public synchronized String generateAlias(TableConfiguration tabConfig) {
		if (this.autoGeneratedAliases == null) {
			this.autoGeneratedAliases = new ArrayList<>();
		}
		
		int i = 1;
		
		String tableName = DBUtilities.extractTableNameFromFullTableName(tabConfig.getTableName());
		
		String alias = tableName + "_" + i;
		
		while (this.autoGeneratedAliases.contains(alias)) {
			alias = tableName + "_" + ++i;
		}
		
		this.autoGeneratedAliases.add(alias);
		
		return alias;
	}
	
	public synchronized void fullLoad() throws DBException {
		
		if (this.fullLoaded) {
			return;
		}
		if (!utilities.stringHasValue(this.getTableAlias())) {
			this.setTableAlias(generateAlias(this));
		}
		
		super.fullLoad();
		
		if (this.hasParentRefInfo()) {
			for (ParentTable ref : this.getParentRefInfo()) {
				TableConfiguration fullLoadedTab = findFullConfiguredConfInAllRelatedTable(ref.getTableName());
				
				if (fullLoadedTab != null) {
					ref.clone(fullLoadedTab);
				} else {
					ref.setRelatedSyncConfiguration(getRelatedSyncConfiguration());
					ref.fullLoad();
				}
				
				ref.setTableAlias(generateAlias(ref));
				
				if (ref.useSharedPKKey()) {
					fullLoadedTab = findFullConfiguredConfInAllRelatedTable(ref.getSharedKeyRefInfo().getTableName());
					
					if (fullLoadedTab != null) {
						ref.getSharedKeyRefInfo().clone(fullLoadedTab);
					} else {
						ref.getSharedKeyRefInfo().fullLoad();
					}
					
					ref.getSharedKeyRefInfo().setTableAlias(generateAlias(ref.getSharedKeyRefInfo()));
				}
				
			}
		}
		
		OpenConnection srcConn = this.getRelatedAppInfo().openConnection();
		
		try {
			
			if (utilities.arrayHasElement(this.selfJoinTables)) {
				for (AuxExtractTable t : this.selfJoinTables) {
					t.setParentConf(this);
					
					TableConfiguration fullLoadedTab = findFullConfiguredConfInAllRelatedTable(t.getTableName());
					
					if (fullLoadedTab != null) {
						t.clone(fullLoadedTab);
					} else {
						t.fullLoad(srcConn);
					}
					
					t.setTableAlias(this.generateAlias(t));
				}
			}
			
			if (utilities.arrayHasElement(this.extraTableDataSource)) {
				for (TableDataSourceConfig t : this.extraTableDataSource) {
					
					TableConfiguration fullLoadedTab = findFullConfiguredConfInAllRelatedTable(t.getTableName());
					
					if (fullLoadedTab != null) {
						t.clone(fullLoadedTab);
						
						t.setTableAlias(this.generateAlias(t));
					} else {
						t.fullLoad(srcConn);
					}
					
					t.setRelatedSrcConf(this);
					
					if (t.useSharedPKKey()) {
						fullLoadedTab = findFullConfiguredConfInAllRelatedTable(t.getSharedKeyRefInfo().getTableName());
						
						if (fullLoadedTab != null) {
							t.getSharedKeyRefInfo().clone(fullLoadedTab);
						} else {
							t.getSharedKeyRefInfo().fullLoad();
						}
						
						t.getSharedKeyRefInfo().setTableAlias(generateAlias(t.getSharedKeyRefInfo()));
					}
					
				}
				
			}
			
			if (utilities.arrayHasElement(this.extraQueryDataSource)) {
				for (QueryDataSourceConfig query : this.extraQueryDataSource) {
					query.setRelatedSrcConf(this);
					query.fullLoad(srcConn);
				}
			}
		}
		catch (Exception e) {
			srcConn.finalizeConnection();
			
			e.printStackTrace();
			
			throw new RuntimeException(e);
		}
		
		this.fullLoaded = true;
	}
	
	public void setFullLoaded(boolean fullLoaded) {
		this.fullLoaded = fullLoaded;
	}
	
	public QueryDataSourceConfig findAdditionalDataSrc(String dsName) {
		if (!utilities.arrayHasElement(this.extraQueryDataSource)) {
			return null;
		}
		
		for (QueryDataSourceConfig src : this.extraQueryDataSource) {
			if (src.getName().equals(dsName)) {
				return src;
			}
		}
		
		throw new ForbiddenOperationException("The table '" + dsName + "'cannot be foud on the mapping src tables");
	}
	
	public boolean isFullLoaded() {
		return this.fullLoaded;
	}
	
	public static SrcConf fastCreate(AbstractTableConfiguration tableConfig) {
		SrcConf src = new SrcConf();
		
		src.clone(src);
		
		return src;
	}
	
	@Override
	public void setParentConf(EtlDataConfiguration parent) {
		super.setParentConf((EtlItemConfiguration) parent);
	}
	
	@Override
	@JsonIgnore
	public EtlItemConfiguration getParentConf() {
		return (EtlItemConfiguration) super.getParentConf();
	}
	
	@Override
	public AppInfo getRelatedAppInfo() {
		return getMainApp();
	}
	
	@Override
	public void tryToDiscoverySharedKeyInfo(Connection conn) throws DBException {
		super.tryToDiscoverySharedKeyInfo(conn);
		
		if (useSharedPKKey()) {
			//Parce the shared parent to datasource
			utilities.updateOnArray(this.getParentRefInfo(), getSharedKeyRefInfo(),
			    SharedPkDataSource.generateFromSrcConfSharedPkParent(this));
		}
	}
	
	@JsonIgnore
	public List<EtlAdditionalDataSource> getAvaliableExtraDataSource() {
		List<EtlAdditionalDataSource> ds = new ArrayList<>();
		
		if (useSharedPKKey()) {
			ds.add((EtlAdditionalDataSource) getSharedKeyRefInfo());
		}
		
		if (utilities.arrayHasElement(this.extraTableDataSource)) {
			ds.addAll(utilities.parseList(this.extraTableDataSource, EtlAdditionalDataSource.class));
		}
		
		if (utilities.arrayHasElement(this.extraQueryDataSource)) {
			ds.addAll(utilities.parseList(this.extraQueryDataSource, EtlAdditionalDataSource.class));
		}
		
		return ds;
	}
	
	/**
	 * Generate all avaliable fields on this srcConf, this fields will include all field from
	 * {@link #getFields()} and the fields from all {@link #extraTableDataSource} Note that the
	 * duplicated fields will only be included once
	 * 
	 * @return
	 */
	public List<Field> generateAllAvaliableFields() {
		List<Field> fields = new ArrayList<>();
		
		for (Field f : this.getFields()) {
			fields.add(f);
		}
		
		if (this.extraTableDataSource != null) {
			
			for (EtlAdditionalDataSource ds : this.extraTableDataSource) {
				for (Field f : ds.getFields()) {
					
					if (!fields.contains(f)) {
						fields.add(f);
					}
				}
			}
		}
		
		return fields;
	}
	
	public boolean hasExtraTableDataSourceConfig() {
		return utilities.arrayHasElement(this.extraTableDataSource);
	}
	
	public boolean hasExtraQueryDataSourceConfig() {
		return utilities.arrayHasElement(this.extraQueryDataSource);
	}
	
}
